const Instruction = @import("instruction.zig").Instruction;

pub const INSTRUCTIONS_EXTENDED = [_]Instruction{
    .{ // RLC B
        .opcode = 0x00,
        .cycles = 2,
        .class = .rlc,
        .dst = .{ .r8 = .b },
    },
    .{ // RLC C
        .opcode = 0x01,
        .cycles = 2,
        .class = .rlc,
        .dst = .{ .r8 = .c },
    },
    .{ // RLC D
        .opcode = 0x02,
        .cycles = 2,
        .class = .rlc,
        .dst = .{ .r8 = .d },
    },
    .{ // RLC E
        .opcode = 0x03,
        .cycles = 2,
        .class = .rlc,
        .dst = .{ .r8 = .e },
    },
    .{ // RLC H
        .opcode = 0x04,
        .cycles = 2,
        .class = .rlc,
        .dst = .{ .r8 = .h },
    },
    .{ // RLC L
        .opcode = 0x05,
        .cycles = 2,
        .class = .rlc,
        .dst = .{ .r8 = .l },
    },
    .{ // RLC (HL)
        .opcode = 0x06,
        .cycles = 4,
        .class = .rlc,
        .dst = .{ .r88 = .{ .h, .l } },
        .dst_ptr = true,
    },
    .{ // RLC A
        .opcode = 0x07,
        .cycles = 2,
        .class = .rlc,
        .dst = .{ .r8 = .a },
    },
    .{ // RRC B
        .opcode = 0x08,
        .cycles = 2,
        .class = .rrc,
        .dst = .{ .r8 = .b },
    },
    .{ // RRC C
        .opcode = 0x09,
        .cycles = 2,
        .class = .rrc,
        .dst = .{ .r8 = .c },
    },
    .{ // RRC D
        .opcode = 0x0A,
        .cycles = 2,
        .class = .rrc,
        .dst = .{ .r8 = .d },
    },
    .{ // RRC E
        .opcode = 0x0B,
        .cycles = 2,
        .class = .rrc,
        .dst = .{ .r8 = .e },
    },
    .{ // RRC H
        .opcode = 0x0C,
        .cycles = 2,
        .class = .rrc,
        .dst = .{ .r8 = .h },
    },
    .{ // RRC L
        .opcode = 0x0D,
        .cycles = 2,
        .class = .rrc,
        .dst = .{ .r8 = .l },
    },
    .{ // RRC (HL)
        .opcode = 0x0E,
        .cycles = 4,
        .class = .rrc,
        .dst = .{ .r88 = .{ .h, .l } },
        .dst_ptr = true,
    },
    .{ // RRC A
        .opcode = 0x0F,
        .cycles = 2,
        .class = .rrc,
        .dst = .{ .r8 = .a },
    },
    .{ // RL B
        .opcode = 0x10,
        .cycles = 2,
        .class = .rl,
        .dst = .{ .r8 = .b },
    },
    .{ // RL C
        .opcode = 0x11,
        .cycles = 2,
        .class = .rl,
        .dst = .{ .r8 = .c },
    },
    .{ // RL D
        .opcode = 0x12,
        .cycles = 2,
        .class = .rl,
        .dst = .{ .r8 = .d },
    },
    .{ // RL E
        .opcode = 0x13,
        .cycles = 2,
        .class = .rl,
        .dst = .{ .r8 = .e },
    },
    .{ // RL H
        .opcode = 0x14,
        .cycles = 2,
        .class = .rl,
        .dst = .{ .r8 = .h },
    },
    .{ // RL L
        .opcode = 0x15,
        .cycles = 2,
        .class = .rl,
        .dst = .{ .r8 = .l },
    },
    .{ // RL (HL)
        .opcode = 0x16,
        .cycles = 4,
        .class = .rl,
        .dst = .{ .r88 = .{ .h, .l } },
        .dst_ptr = true,
    },
    .{ // RL A
        .opcode = 0x17,
        .cycles = 2,
        .class = .rl,
        .dst = .{ .r8 = .a },
    },
    .{ // RR B
        .opcode = 0x18,
        .cycles = 2,
        .class = .rr,
        .dst = .{ .r8 = .b },
    },
    .{ // RR C
        .opcode = 0x19,
        .cycles = 2,
        .class = .rr,
        .dst = .{ .r8 = .c },
    },
    .{ // RR D
        .opcode = 0x1A,
        .cycles = 2,
        .class = .rr,
        .dst = .{ .r8 = .d },
    },
    .{ // RR E
        .opcode = 0x1B,
        .cycles = 2,
        .class = .rr,
        .dst = .{ .r8 = .e },
    },
    .{ // RR H
        .opcode = 0x1C,
        .cycles = 2,
        .class = .rr,
        .dst = .{ .r8 = .h },
    },
    .{ // RR L
        .opcode = 0x1D,
        .cycles = 2,
        .class = .rr,
        .dst = .{ .r8 = .l },
    },
    .{ // RR (HL)
        .opcode = 0x1E,
        .cycles = 4,
        .class = .rr,
        .dst = .{ .r88 = .{ .h, .l } },
        .dst_ptr = true,
    },
    .{ // RR A
        .opcode = 0x1F,
        .cycles = 2,
        .class = .rr,
        .dst = .{ .r8 = .a },
    },
    .{ // SLA B
        .opcode = 0x20,
        .cycles = 2,
        .class = .sla,
        .dst = .{ .r8 = .b },
    },
    .{ // SLA C
        .opcode = 0x21,
        .cycles = 2,
        .class = .sla,
        .dst = .{ .r8 = .c },
    },
    .{ // SLA D
        .opcode = 0x22,
        .cycles = 2,
        .class = .sla,
        .dst = .{ .r8 = .d },
    },
    .{ // SLA E
        .opcode = 0x23,
        .cycles = 2,
        .class = .sla,
        .dst = .{ .r8 = .e },
    },
    .{ // SLA H
        .opcode = 0x24,
        .cycles = 2,
        .class = .sla,
        .dst = .{ .r8 = .h },
    },
    .{ // SLA L
        .opcode = 0x25,
        .cycles = 2,
        .class = .sla,
        .dst = .{ .r8 = .l },
    },
    .{ // SLA (HL)
        .opcode = 0x26,
        .cycles = 4,
        .class = .sla,
        .dst = .{ .r88 = .{ .h, .l } },
        .dst_ptr = true,
    },
    .{ // SLA A
        .opcode = 0x27,
        .cycles = 2,
        .class = .sla,
        .dst = .{ .r8 = .a },
    },
    .{ // SRA B
        .opcode = 0x28,
        .cycles = 2,
        .class = .sra,
        .dst = .{ .r8 = .b },
    },
    .{ // SRA C
        .opcode = 0x29,
        .cycles = 2,
        .class = .sra,
        .dst = .{ .r8 = .c },
    },
    .{ // SRA D
        .opcode = 0x2A,
        .cycles = 2,
        .class = .sra,
        .dst = .{ .r8 = .d },
    },
    .{ // SRA E
        .opcode = 0x2B,
        .cycles = 2,
        .class = .sra,
        .dst = .{ .r8 = .e },
    },
    .{ // SRA H
        .opcode = 0x2C,
        .cycles = 2,
        .class = .sra,
        .dst = .{ .r8 = .h },
    },
    .{ // SRA L
        .opcode = 0x2D,
        .cycles = 2,
        .class = .sra,
        .dst = .{ .r8 = .l },
    },
    .{ // SRA (HL)
        .opcode = 0x2E,
        .cycles = 4,
        .class = .sra,
        .dst = .{ .r88 = .{ .h, .l } },
        .dst_ptr = true,
    },
    .{ // SRA A
        .opcode = 0x2F,
        .cycles = 2,
        .class = .sra,
        .dst = .{ .r8 = .a },
    },
    .{ // SWAP B
        .opcode = 0x30,
        .cycles = 2,
        .class = .swap,
        .dst = .{ .r8 = .b },
    },
    .{ // SWAP C
        .opcode = 0x31,
        .cycles = 2,
        .class = .swap,
        .dst = .{ .r8 = .c },
    },
    .{ // SWAP D
        .opcode = 0x32,
        .cycles = 2,
        .class = .swap,
        .dst = .{ .r8 = .d },
    },
    .{ // SWAP E
        .opcode = 0x33,
        .cycles = 2,
        .class = .swap,
        .dst = .{ .r8 = .e },
    },
    .{ // SWAP H
        .opcode = 0x34,
        .cycles = 2,
        .class = .swap,
        .dst = .{ .r8 = .h },
    },
    .{ // SWAP L
        .opcode = 0x35,
        .cycles = 2,
        .class = .swap,
        .dst = .{ .r8 = .l },
    },
    .{ // SWAP (HL)
        .opcode = 0x36,
        .cycles = 4,
        .class = .swap,
        .dst = .{ .r88 = .{ .h, .l } },
        .dst_ptr = true,
    },
    .{ // SWAP A
        .opcode = 0x37,
        .cycles = 2,
        .class = .swap,
        .dst = .{ .r8 = .a },
    },
    .{ // SRL B
        .opcode = 0x38,
        .cycles = 2,
        .class = .srl,
        .dst = .{ .r8 = .b },
    },
    .{ // SRL C
        .opcode = 0x39,
        .cycles = 2,
        .class = .srl,
        .dst = .{ .r8 = .c },
    },
    .{ // SRL D
        .opcode = 0x3A,
        .cycles = 2,
        .class = .srl,
        .dst = .{ .r8 = .d },
    },
    .{ // SRL E
        .opcode = 0x3B,
        .cycles = 2,
        .class = .srl,
        .dst = .{ .r8 = .e },
    },
    .{ // SRL H
        .opcode = 0x3C,
        .cycles = 2,
        .class = .srl,
        .dst = .{ .r8 = .h },
    },
    .{ // SRL L
        .opcode = 0x3D,
        .cycles = 2,
        .class = .srl,
        .dst = .{ .r8 = .l },
    },
    .{ // SRL (HL)
        .opcode = 0x3E,
        .cycles = 4,
        .class = .srl,
        .dst = .{ .r88 = .{ .h, .l } },
        .dst_ptr = true,
    },
    .{ // SRL A
        .opcode = 0x3F,
        .cycles = 2,
        .class = .srl,
        .dst = .{ .r8 = .a },
    },
    .{ // RES 0,B
        .opcode = 0x40,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .b },
    },
    .{ // BIT 0,C
        .opcode = 0x41,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .c },
    },
    .{ // BIT 0,D
        .opcode = 0x42,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .d },
    },
    .{ // BIT 0,E
        .opcode = 0x43,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .e },
    },
    .{ // BIT 0,H
        .opcode = 0x44,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .h },
    },
    .{ // BIT 0,L
        .opcode = 0x45,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .l },
    },
    .{ // BIT 0,(HL)
        .opcode = 0x46,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 0 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // BIT 0,A
        .opcode = 0x47,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .a },
    },
    .{ // BIT 1,B
        .opcode = 0x48,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .b },
    },
    .{ // BIT 1,C
        .opcode = 0x49,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .c },
    },
    .{ // BIT 1,D
        .opcode = 0x4A,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .d },
    },
    .{ // BIT 1,E
        .opcode = 0x4B,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .e },
    },
    .{ // BIT 1,H
        .opcode = 0x4C,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .h },
    },
    .{ // BIT 1,L
        .opcode = 0x4D,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .l },
    },
    .{ // BIT 1,(HL)
        .opcode = 0x4E,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 1 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // BIT 1,A
        .opcode = 0x4F,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .a },
    },
    .{ // BIT 2,B
        .opcode = 0x50,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .b },
    },
    .{ // BIT 2,C
        .opcode = 0x51,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .c },
    },
    .{ // BIT 2,D
        .opcode = 0x52,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .d },
    },
    .{ // BIT 2,E
        .opcode = 0x53,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .e },
    },
    .{ // BIT 2,H
        .opcode = 0x54,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .h },
    },
    .{ // BIT 2,L
        .opcode = 0x55,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .l },
    },
    .{ // BIT 2,(HL)
        .opcode = 0x56,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 2 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // BIT 2,A
        .opcode = 0x57,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .a },
    },
    .{ // BIT 3,B
        .opcode = 0x58,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .b },
    },
    .{ // BIT 3,C
        .opcode = 0x59,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .c },
    },
    .{ // BIT 3,D
        .opcode = 0x5A,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .d },
    },
    .{ // BIT 3,E
        .opcode = 0x5B,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .e },
    },
    .{ // BIT 3,H
        .opcode = 0x5C,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .h },
    },
    .{ // BIT 3,L
        .opcode = 0x5D,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .l },
    },
    .{ // BIT 3,(HL)
        .opcode = 0x5E,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 3 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // BIT 3,A
        .opcode = 0x5F,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .a },
    },
    .{ // BIT 4,B
        .opcode = 0x60,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .b },
    },
    .{ // BIT 4,C
        .opcode = 0x61,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .c },
    },
    .{ // BIT 4,D
        .opcode = 0x62,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .d },
    },
    .{ // BIT 4,E
        .opcode = 0x63,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .e },
    },
    .{ // BIT 4,H
        .opcode = 0x64,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .h },
    },
    .{ // BIT 4,L
        .opcode = 0x65,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .l },
    },
    .{ // BIT 4,(HL)
        .opcode = 0x66,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 4 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // BIT 4,A
        .opcode = 0x67,
        .cycles = 4,
        .class = .bit,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .a },
    },
    .{ // BIT 5,B
        .opcode = 0x68,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .b },
    },
    .{ // BIT 5,C
        .opcode = 0x69,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .c },
    },
    .{ // BIT 5,D
        .opcode = 0x6A,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .d },
    },
    .{ // BIT 5,E
        .opcode = 0x6B,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .e },
    },
    .{ // BIT 5,H
        .opcode = 0x6C,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .h },
    },
    .{ // BIT 5,L
        .opcode = 0x6D,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .l },
    },
    .{ // BIT 5,(HL)
        .opcode = 0x6E,
        .cycles = 5,
        .class = .bit,
        .dst = .{ .bit = 5 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // BIT 5,A
        .opcode = 0x6F,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .a },
    },
    .{ // BIT 6,B
        .opcode = 0x70,
        .cycles = 6,
        .class = .bit,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .b },
    },
    .{ // BIT 6,C
        .opcode = 0x71,
        .cycles = 6,
        .class = .bit,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .c },
    },
    .{ // BIT 6,D
        .opcode = 0x72,
        .cycles = 6,
        .class = .bit,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .d },
    },
    .{ // BIT 6,E
        .opcode = 0x73,
        .cycles = 6,
        .class = .bit,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .e },
    },
    .{ // BIT 6,H
        .opcode = 0x74,
        .cycles = 6,
        .class = .bit,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .h },
    },
    .{ // BIT 6,L
        .opcode = 0x75,
        .cycles = 6,
        .class = .bit,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .l },
    },
    .{ // BIT 6,(HL)
        .opcode = 0x76,
        .cycles = 6,
        .class = .bit,
        .dst = .{ .bit = 6 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // BIT 6,A
        .opcode = 0x77,
        .cycles = 6,
        .class = .bit,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .a },
    },
    .{ // BIT 7,B
        .opcode = 0x78,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .b },
    },
    .{ // BIT 7,C
        .opcode = 0x79,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .c },
    },
    .{ // BIT 7,D
        .opcode = 0x7A,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .d },
    },
    .{ // BIT 7,E
        .opcode = 0x7B,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .e },
    },
    .{ // BIT 7,H
        .opcode = 0x7C,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .h },
    },
    .{ // BIT 7,L
        .opcode = 0x7D,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .l },
    },
    .{ // BIT 7,(HL)
        .opcode = 0x7E,
        .cycles = 7,
        .class = .bit,
        .dst = .{ .bit = 7 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // BIT 7,A
        .opcode = 0x7F,
        .cycles = 2,
        .class = .bit,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .a },
    },
    .{ // RES 0,B
        .opcode = 0x80,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .b },
    },
    .{ // RES 0,C
        .opcode = 0x81,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .c },
    },
    .{ // RES 0,D
        .opcode = 0x82,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .d },
    },
    .{ // RES 0,E
        .opcode = 0x83,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .e },
    },
    .{ // RES 0,H
        .opcode = 0x84,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .h },
    },
    .{ // RES 0,L
        .opcode = 0x85,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .l },
    },
    .{ // RES 0,(HL)
        .opcode = 0x86,
        .cycles = 4,
        .class = .res,
        .dst = .{ .bit = 0 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // RES 0,A
        .opcode = 0x87,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .a },
    },
    .{ // RES 1,B
        .opcode = 0x88,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .b },
    },
    .{ // RES 1,C
        .opcode = 0x89,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .c },
    },
    .{ // RES 1,D
        .opcode = 0x8A,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .d },
    },
    .{ // RES 1,E
        .opcode = 0x8B,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .e },
    },
    .{ // RES 1,H
        .opcode = 0x8C,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .h },
    },
    .{ // RES 1,L
        .opcode = 0x8D,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .l },
    },
    .{ // RES 1,(HL)
        .opcode = 0x8E,
        .cycles = 4,
        .class = .res,
        .dst = .{ .bit = 1 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // RES 1,A
        .opcode = 0x8F,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .a },
    },
    .{ // RES 2,B
        .opcode = 0x90,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .b },
    },
    .{ // RES 2,C
        .opcode = 0x91,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .c },
    },
    .{ // RES 2,D
        .opcode = 0x92,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .d },
    },
    .{ // RES 2,E
        .opcode = 0x93,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .e },
    },
    .{ // RES 2,H
        .opcode = 0x94,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .h },
    },
    .{ // RES 2,L
        .opcode = 0x95,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .l },
    },
    .{ // RES 2,(HL)
        .opcode = 0x96,
        .cycles = 4,
        .class = .res,
        .dst = .{ .bit = 2 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // RES 2,A
        .opcode = 0x97,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .a },
    },
    .{ // RES 3,B
        .opcode = 0x98,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .b },
    },
    .{ // RES 3,C
        .opcode = 0x99,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .c },
    },
    .{ // RES 3,D
        .opcode = 0x9A,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .d },
    },
    .{ // RES 3,E
        .opcode = 0x9B,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .e },
    },
    .{ // RES 3,H
        .opcode = 0x9C,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .h },
    },
    .{ // RES 3,L
        .opcode = 0x9D,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .l },
    },
    .{ // RES 3,(HL)
        .opcode = 0x9E,
        .cycles = 4,
        .class = .res,
        .dst = .{ .bit = 3 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // RES 3,A
        .opcode = 0x9F,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .a },
    },
    .{ // RES 4,B
        .opcode = 0xA0,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .b },
    },
    .{ // RES 4,C
        .opcode = 0xA1,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .c },
    },
    .{ // RES 4,D
        .opcode = 0xA2,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .d },
    },
    .{ // RES 4,E
        .opcode = 0xA3,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .e },
    },
    .{ // RES 4,H
        .opcode = 0xA4,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .h },
    },
    .{ // RES 4,L
        .opcode = 0xA5,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .l },
    },
    .{ // RES 4,(HL)
        .opcode = 0xA6,
        .cycles = 4,
        .class = .res,
        .dst = .{ .bit = 4 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // RES 4,A
        .opcode = 0xA7,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .a },
    },
    .{ // RES 5,B
        .opcode = 0xA8,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .b },
    },
    .{ // RES 5,C
        .opcode = 0xA9,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .c },
    },
    .{ // RES 5,D
        .opcode = 0xAA,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .d },
    },
    .{ // RES 5,E
        .opcode = 0xAB,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .e },
    },
    .{ // RES 5,H
        .opcode = 0xAC,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .h },
    },
    .{ // RES 5,L
        .opcode = 0xAD,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .l },
    },
    .{ // RES 5,(HL)
        .opcode = 0xAE,
        .cycles = 4,
        .class = .res,
        .dst = .{ .bit = 5 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // RES 5,A
        .opcode = 0xAF,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .a },
    },
    .{ // RES 6,B
        .opcode = 0xB0,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .b },
    },
    .{ // RES 6,C
        .opcode = 0xB1,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .c },
    },
    .{ // RES 6,D
        .opcode = 0xB2,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .d },
    },
    .{ // RES 6,E
        .opcode = 0xB3,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .e },
    },
    .{ // RES 6,H
        .opcode = 0xB4,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .h },
    },
    .{ // RES 6,L
        .opcode = 0xB5,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .l },
    },
    .{ // RES 6,(HL)
        .opcode = 0xB6,
        .cycles = 4,
        .class = .res,
        .dst = .{ .bit = 6 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // RES 6,A
        .opcode = 0xB7,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .a },
    },
    .{ // RES 7,B
        .opcode = 0xB8,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .b },
    },
    .{ // RES 7,C
        .opcode = 0xB9,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .c },
    },
    .{ // RES 7,D
        .opcode = 0xBA,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .d },
    },
    .{ // RES 7,E
        .opcode = 0xBB,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .e },
    },
    .{ // RES 7,H
        .opcode = 0xBC,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .h },
    },
    .{ // RES 7,L
        .opcode = 0xBD,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .l },
    },
    .{ // RES 7,(HL)
        .opcode = 0xBE,
        .cycles = 4,
        .class = .res,
        .dst = .{ .bit = 7 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // RES 7,A
        .opcode = 0xBF,
        .cycles = 2,
        .class = .res,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .a },
    },
    .{ // SET 0,B
        .opcode = 0xC0,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .b },
    },
    .{ // SET 0,C
        .opcode = 0xC1,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .c },
    },
    .{ // SET 0,D
        .opcode = 0xC2,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .d },
    },
    .{ // SET 0,E
        .opcode = 0xC3,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .e },
    },
    .{ // SET 0,H
        .opcode = 0xC4,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .h },
    },
    .{ // SET 0,L
        .opcode = 0xC5,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .l },
    },
    .{ // SET 0,(HL)
        .opcode = 0xC6,
        .cycles = 4,
        .class = .set,
        .dst = .{ .bit = 0 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // SET 0,A
        .opcode = 0xC7,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 0 },
        .src = .{ .r8 = .a },
    },
    .{ // SET 1,B
        .opcode = 0xC8,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .b },
    },
    .{ // SET 1,C
        .opcode = 0xC9,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .c },
    },
    .{ // SET 1,D
        .opcode = 0xCA,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .d },
    },
    .{ // SET 1,E
        .opcode = 0xCB,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .e },
    },
    .{ // SET 1,H
        .opcode = 0xCC,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .h },
    },
    .{ // SET 1,L
        .opcode = 0xCD,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .l },
    },
    .{ // SET 1,(HL)
        .opcode = 0xCE,
        .cycles = 4,
        .class = .set,
        .dst = .{ .bit = 1 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // SET 1,A
        .opcode = 0xCF,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 1 },
        .src = .{ .r8 = .a },
    },
    .{ // SET 2,B
        .opcode = 0xD0,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .b },
    },
    .{ // SET 2,C
        .opcode = 0xD1,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .c },
    },
    .{ // SET 2,D
        .opcode = 0xD2,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .d },
    },
    .{ // SET 2,E
        .opcode = 0xD3,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .e },
    },
    .{ // SET 2,H
        .opcode = 0xD4,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .h },
    },
    .{ // SET 2,L
        .opcode = 0xD5,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .l },
    },
    .{ // SET 2,(HL)
        .opcode = 0xD6,
        .cycles = 4,
        .class = .set,
        .dst = .{ .bit = 2 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // SET 2,A
        .opcode = 0xD7,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 2 },
        .src = .{ .r8 = .a },
    },
    .{ // SET 3,B
        .opcode = 0xD8,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .b },
    },
    .{ // SET 3,C
        .opcode = 0xD9,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .c },
    },
    .{ // SET 3,D
        .opcode = 0xDA,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .d },
    },
    .{ // SET 3,E
        .opcode = 0xDB,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .e },
    },
    .{ // SET 3,H
        .opcode = 0xDC,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .h },
    },
    .{ // SET 3,L
        .opcode = 0xDD,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .l },
    },
    .{ // SET 3,(HL)
        .opcode = 0xDE,
        .cycles = 4,
        .class = .set,
        .dst = .{ .bit = 3 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // SET 3,A
        .opcode = 0xDF,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 3 },
        .src = .{ .r8 = .a },
    },
    .{ // SET 4,B
        .opcode = 0xE0,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .b },
    },
    .{ // SET 4,C
        .opcode = 0xE1,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .c },
    },
    .{ // SET 4,D
        .opcode = 0xE2,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .d },
    },
    .{ // SET 4,E
        .opcode = 0xE3,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .e },
    },
    .{ // SET 4,H
        .opcode = 0xE4,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .h },
    },
    .{ // SET 4,L
        .opcode = 0xE5,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .l },
    },
    .{ // SET 4,(HL)
        .opcode = 0xE6,
        .cycles = 4,
        .class = .set,
        .dst = .{ .bit = 4 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // SET 4,A
        .opcode = 0xE7,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 4 },
        .src = .{ .r8 = .a },
    },
    .{ // SET 5,B
        .opcode = 0xE8,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .b },
    },
    .{ // SET 5,C
        .opcode = 0xE9,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .c },
    },
    .{ // SET 5,D
        .opcode = 0xEA,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .d },
    },
    .{ // SET 5,E
        .opcode = 0xEB,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .e },
    },
    .{ // SET 5,H
        .opcode = 0xEC,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .h },
    },
    .{ // SET 5,L
        .opcode = 0xED,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .l },
    },
    .{ // SET 5,(HL)
        .opcode = 0xEE,
        .cycles = 4,
        .class = .set,
        .dst = .{ .bit = 5 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // SET 5,A
        .opcode = 0xEF,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 5 },
        .src = .{ .r8 = .a },
    },
    .{ // SET 6,B
        .opcode = 0xF0,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .b },
    },
    .{ // SET 6,C
        .opcode = 0xF1,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .c },
    },
    .{ // SET 6,D
        .opcode = 0xF2,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .d },
    },
    .{ // SET 6,E
        .opcode = 0xF3,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .e },
    },
    .{ // SET 6,H
        .opcode = 0xF4,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .h },
    },
    .{ // SET 6,L
        .opcode = 0xF5,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .l },
    },
    .{ // SET 6,(HL)
        .opcode = 0xF6,
        .cycles = 4,
        .class = .set,
        .dst = .{ .bit = 6 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // SET 6,A
        .opcode = 0xF7,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 6 },
        .src = .{ .r8 = .a },
    },
    .{ // SET 7,B
        .opcode = 0xF8,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .b },
    },
    .{ // SET 7,C
        .opcode = 0xF9,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .c },
    },
    .{ // SET 7,D
        .opcode = 0xFA,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .d },
    },
    .{ // SET 7,E
        .opcode = 0xFB,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .e },
    },
    .{ // SET 7,H
        .opcode = 0xFC,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .h },
    },
    .{ // SET 7,L
        .opcode = 0xFD,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .l },
    },
    .{ // SET 7,(HL)
        .opcode = 0xFE,
        .cycles = 4,
        .class = .set,
        .dst = .{ .bit = 7 },
        .src = .{ .r88 = .{ .h, .l } },
        .src_ptr = true,
    },
    .{ // SET 7,A
        .opcode = 0xFF,
        .cycles = 2,
        .class = .set,
        .dst = .{ .bit = 7 },
        .src = .{ .r8 = .a },
    },
};

test "Extended instruction table opcodes" {
    const expectEq = @import("std").testing.expectEq;

    for (INSTRUCTIONS_EXTENDED) |instruction, i| {
        expectEq(i, instruction.opcode);
    }
}
